/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ReservationInput = IDL.Record({
  'date' : IDL.Text,
  'time' : IDL.Text,
  'guestName' : IDL.Text,
  'email' : IDL.Text,
  'partySize' : IDL.Nat,
  'phone' : IDL.Text,
  'specialNotes' : IDL.Text,
});
export const ReservationStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const Reservation = IDL.Record({
  'status' : ReservationStatus,
  'date' : IDL.Text,
  'createdAt' : Time,
  'time' : IDL.Text,
  'guestName' : IDL.Text,
  'email' : IDL.Text,
  'partySize' : IDL.Nat,
  'phone' : IDL.Text,
  'specialNotes' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ReservationUpdate = IDL.Record({
  'status' : ReservationStatus,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'guestName' : IDL.Text,
  'email' : IDL.Text,
  'partySize' : IDL.Nat,
  'phone' : IDL.Text,
  'specialNotes' : IDL.Text,
});
export const UpdateStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'confirmed' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelReservation' : IDL.Func([IDL.Nat], [], []),
  'confirmReservation' : IDL.Func([IDL.Nat], [], []),
  'createReservation' : IDL.Func([ReservationInput], [IDL.Nat], []),
  'deleteReservation' : IDL.Func([IDL.Nat], [], []),
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCancelledReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getConfirmedReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getPendingReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getReservation' : IDL.Func([IDL.Nat], [IDL.Opt(Reservation)], ['query']),
  'getReservationCountsByDate' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'cancelled' : IDL.Nat,
          'pending' : IDL.Nat,
          'confirmed' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getReservationCountsByStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'cancelled' : IDL.Nat,
          'pending' : IDL.Nat,
          'confirmed' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getReservationsByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Reservation)],
      ['query'],
    ),
  'getReservationsByGuestName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Reservation)],
      ['query'],
    ),
  'getReservationsByPartySize' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Reservation)],
      ['query'],
    ),
  'getReservationsByStatus' : IDL.Func(
      [ReservationStatus],
      [IDL.Vec(Reservation)],
      ['query'],
    ),
  'getUpcomingReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateReservation' : IDL.Func([IDL.Nat, ReservationUpdate], [], []),
  'updateReservationStatus' : IDL.Func([IDL.Nat, UpdateStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ReservationInput = IDL.Record({
    'date' : IDL.Text,
    'time' : IDL.Text,
    'guestName' : IDL.Text,
    'email' : IDL.Text,
    'partySize' : IDL.Nat,
    'phone' : IDL.Text,
    'specialNotes' : IDL.Text,
  });
  const ReservationStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Reservation = IDL.Record({
    'status' : ReservationStatus,
    'date' : IDL.Text,
    'createdAt' : Time,
    'time' : IDL.Text,
    'guestName' : IDL.Text,
    'email' : IDL.Text,
    'partySize' : IDL.Nat,
    'phone' : IDL.Text,
    'specialNotes' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ReservationUpdate = IDL.Record({
    'status' : ReservationStatus,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'guestName' : IDL.Text,
    'email' : IDL.Text,
    'partySize' : IDL.Nat,
    'phone' : IDL.Text,
    'specialNotes' : IDL.Text,
  });
  const UpdateStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelReservation' : IDL.Func([IDL.Nat], [], []),
    'confirmReservation' : IDL.Func([IDL.Nat], [], []),
    'createReservation' : IDL.Func([ReservationInput], [IDL.Nat], []),
    'deleteReservation' : IDL.Func([IDL.Nat], [], []),
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCancelledReservations' : IDL.Func(
        [],
        [IDL.Vec(Reservation)],
        ['query'],
      ),
    'getConfirmedReservations' : IDL.Func(
        [],
        [IDL.Vec(Reservation)],
        ['query'],
      ),
    'getPendingReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getReservation' : IDL.Func([IDL.Nat], [IDL.Opt(Reservation)], ['query']),
    'getReservationCountsByDate' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'cancelled' : IDL.Nat,
            'pending' : IDL.Nat,
            'confirmed' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getReservationCountsByStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'cancelled' : IDL.Nat,
            'pending' : IDL.Nat,
            'confirmed' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getReservationsByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Reservation)],
        ['query'],
      ),
    'getReservationsByGuestName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Reservation)],
        ['query'],
      ),
    'getReservationsByPartySize' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Reservation)],
        ['query'],
      ),
    'getReservationsByStatus' : IDL.Func(
        [ReservationStatus],
        [IDL.Vec(Reservation)],
        ['query'],
      ),
    'getUpcomingReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateReservation' : IDL.Func([IDL.Nat, ReservationUpdate], [], []),
    'updateReservationStatus' : IDL.Func([IDL.Nat, UpdateStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };