/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Reservation {
  'status' : ReservationStatus,
  'date' : string,
  'createdAt' : Time,
  'time' : string,
  'guestName' : string,
  'email' : string,
  'partySize' : bigint,
  'phone' : string,
  'specialNotes' : string,
}
export interface ReservationInput {
  'date' : string,
  'time' : string,
  'guestName' : string,
  'email' : string,
  'partySize' : bigint,
  'phone' : string,
  'specialNotes' : string,
}
export type ReservationStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface ReservationUpdate {
  'status' : ReservationStatus,
  'date' : string,
  'time' : string,
  'guestName' : string,
  'email' : string,
  'partySize' : bigint,
  'phone' : string,
  'specialNotes' : string,
}
export type Time = bigint;
export type UpdateStatus = { 'cancelled' : null } |
  { 'confirmed' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelReservation' : ActorMethod<[bigint], undefined>,
  'confirmReservation' : ActorMethod<[bigint], undefined>,
  'createReservation' : ActorMethod<[ReservationInput], bigint>,
  'deleteReservation' : ActorMethod<[bigint], undefined>,
  'getAllReservations' : ActorMethod<[], Array<Reservation>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCancelledReservations' : ActorMethod<[], Array<Reservation>>,
  'getConfirmedReservations' : ActorMethod<[], Array<Reservation>>,
  'getPendingReservations' : ActorMethod<[], Array<Reservation>>,
  'getReservation' : ActorMethod<[bigint], [] | [Reservation]>,
  'getReservationCountsByDate' : ActorMethod<
    [string],
    { 'cancelled' : bigint, 'pending' : bigint, 'confirmed' : bigint }
  >,
  'getReservationCountsByStatus' : ActorMethod<
    [],
    { 'cancelled' : bigint, 'pending' : bigint, 'confirmed' : bigint }
  >,
  'getReservationsByDate' : ActorMethod<[string], Array<Reservation>>,
  'getReservationsByGuestName' : ActorMethod<[string], Array<Reservation>>,
  'getReservationsByPartySize' : ActorMethod<[bigint], Array<Reservation>>,
  'getReservationsByStatus' : ActorMethod<
    [ReservationStatus],
    Array<Reservation>
  >,
  'getUpcomingReservations' : ActorMethod<[], Array<Reservation>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateReservation' : ActorMethod<[bigint, ReservationUpdate], undefined>,
  'updateReservationStatus' : ActorMethod<[bigint, UpdateStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];